# Array

In [1]:
import numpy as np

Vector --> 1-D array

In [14]:
arr1 = np.array([1,2,3]) # round brackets for np and square brackets for array

In [15]:
arr1

array([1, 2, 3])

In [16]:
print(arr1)

[1 2 3]


Matrix --> 2-D array

In [17]:
arr2 = np.array([[1,2,5],[6,7,5,]])

In [18]:
arr2

array([[1, 2, 5],
       [6, 7, 5]])

In [19]:
print(arr2)

[[1 2 5]
 [6 7 5]]


Data shapes --> to check the dimensionality of the object

In [22]:
arr1.shape

(3,)

In [23]:
arr2.shape

(2, 3)

reshape given an array a new shape, without changing its data

In [24]:
arr1.reshape(1,3)

array([[1, 2, 3]])

In [25]:
arr1.reshape(3,1)

array([[1],
       [2],
       [3]])

# Tensor can be defined as a data container. It can be thought of as a multi-dimensional array. Numpy np. array can be used to create tensor of different dimensions such as 1D, 2D, 3D etc. A vector is a 1D tensor, a matrix is a 2D tensor

In [26]:
t1 = np.array([[1,2,3],[4,5,6]])

In [28]:
t2 = np.array([[-2,5,8],[5,6,-9]])

In [30]:
t3 = np.array([t1,t2])
print(t3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-2  5  8]
  [ 5  6 -9]]]


In [31]:
t3.shape

(2, 2, 3)

# Addition

matrix should be of the same matrix

In [32]:
t1 + t2

array([[-1,  7, 11],
       [ 9, 11, -3]])

# Subbtraction --> same rule as addition

In [33]:
t1 - t2

array([[ 3, -3, -5],
       [-1, -1, 15]])

# Transpose

row tarnspose to column or viceversa

In [34]:
t1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
t1

array([[1, 2, 3],
       [4, 5, 6]])

# Dot product of vector

In [38]:
x = np.array([1,2,4])

In [39]:
y = np.array([4,6,7])

In [40]:
np.dot(x,y)

44

In [41]:
import pandas as pd

In [42]:
pd.__version__

'1.4.4'