In [1]:
import numpy as np

# np.empty()

In [2]:
empty = np.empty(shape = (2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

# np.zeros() --> create array full of zeros

In [4]:
zeros = np.zeros(shape = (4,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
zeros = np.zeros(shape = (4,5), dtype=np.int8)
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

# np.ones() --> create array full of one

In [6]:
one = np.ones(shape = (4,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
one = np.ones(shape = (4,5), dtype=np.int8)
one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

# np.full() --> create array full of any number

In [8]:
fulls = np.full(shape = (4,5), fill_value = 3, dtype=np.int8)
fulls

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int8)

In [9]:
fulls = np.full(shape = (4,5), fill_value = "Anand")
fulls

array([['Anand', 'Anand', 'Anand', 'Anand', 'Anand'],
       ['Anand', 'Anand', 'Anand', 'Anand', 'Anand'],
       ['Anand', 'Anand', 'Anand', 'Anand', 'Anand'],
       ['Anand', 'Anand', 'Anand', 'Anand', 'Anand']], dtype='<U5')

# _like functions

In [14]:
like = np.empty_like(one)
like

array([[ 65,   0,   0,   0, 110],
       [  0,   0,   0,  97,   0],
       [  0,   0, 110,   0,   0],
       [  0, 100,   0,   0,   0]], dtype=int8)

same we can do for np.ones,np.zeros,np.empty,np.full

In [15]:
range(0,30)

range(0, 30)

In [17]:
list(range(0,30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [19]:
lsi = np.arange(0,30)

In [20]:
lsi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
lsi = np.arange(0,30)

In [22]:
lsi = np.arange(start = 0, stop = 30)
lsi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
lsi = np.arange(start = 0, stop = 30, step = 2)
lsi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [24]:
lsi = np.arange(start = 0, stop = 30, step = 2, dtype = np.float64)
lsi

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28.])

# Random generator and seeds

In [25]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [26]:
rg = gen(pcg())
rg.normal()

0.4087323185404253

In [27]:
rg = gen(pcg())
rg.normal(size = 5)

array([-0.63425473,  0.12319182, -0.409339  ,  0.75887717, -1.50265783])

In [29]:
rg = gen(pcg())
rg.normal(size = (5,5))

array([[-1.22598934,  1.62372793,  0.43376939,  0.80030853, -1.22929471],
       [-1.07450033, -1.51117671,  0.3721338 , -0.48036639, -0.66236439],
       [ 0.31047157, -0.83675071,  0.59491166,  0.74791486, -0.2267501 ],
       [ 2.028624  , -1.51166116,  0.24615893, -1.13372733,  1.37130497],
       [-0.10078129,  1.46298806, -0.1497453 ,  0.61670283,  0.70935523]])

In [30]:
rg = gen(pcg(seed = 365))
rg.normal(size = (5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])