In [1]:
import numpy as np

In [3]:
data = np.loadtxt("Lending-company-Numeric.csv", delimiter= ',')
data

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

we use np.loadtxt() so that we there is nan values so it will so error 

In [5]:
np.isnan(data)  #given true values when we have missing values and false when we have not missing values.

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [10]:
np.isnan(data).sum()  # given total number oof missing values

0

In [7]:
dataNAN = np.loadtxt("Lending-company-Numeric-NAN.csv", delimiter= ',')  # this is showing error bcause it has NAN values
dataNAN

ValueError: could not convert string '2000;40;365;3121;4241;13621' to float64 at row 0, column 1.

In [11]:
dataNAN = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter= ',')  # this is showing error bcause it has NAN values but when we use genfromtxt then it not hsow any errors
dataNAN

array([nan, nan, nan, ..., nan, nan, nan])

In [12]:
np.isnan(dataNAN).sum()

1043

to fill missing vallues

In [13]:
dataNAN = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter= ',' , filling_values = 0)
dataNAN

array([0., 0., 0., ..., 0., 0., 0.])

In [14]:
np.isnan(dataNAN).sum()

0

In [15]:
dataNAN2 = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter= ',')  
dataNAN2

array([nan, nan, nan, ..., nan, nan, nan])

In [20]:
tempValues = np.nanmax(dataNAN2).round(2) + 1  # all mising values are equal to the max of this array and if the value is equal to max of the array,it is actually missing values.

C:\Users\hp\AppData\Local\Temp\ipykernel_4988\4145475127.py:1: RuntimeWarning: All-NaN slice encountered
  tempValues = np.nanmax(dataNAN2).round(2) + 1  # all mising values are equal to the max of this array and if the value is equal to max of the array,it is actually missing values.


In [17]:
dataNAN = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter= ',' , filling_values = tempValues)
dataNAN

array([nan, nan, nan, ..., nan, nan, nan])