In [1]:
import numpy as np

In [2]:
data = np.genfromtxt("C:/Users/hp/Desktop/Data Analyst/S28 - A Loan Data Example with NumPy/loan-data.csv", delimiter = ';')

In [3]:
data

array([[          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [4.8010226e+07,           nan, 3.5000000e+04, ...,           nan,
                  nan, 9.4529600e+03],
       [5.7693261e+07,           nan, 3.0000000e+04, ...,           nan,
                  nan, 4.6797000e+03],
       ...,
       [5.0415990e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 2.1856400e+03],
       [4.6154151e+07,           nan,           nan, ...,           nan,
                  nan, 3.1994000e+03],
       [6.6055249e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 3.0190000e+02]])

now as we can see that entire first row has nan values so 

In [4]:
data = np.genfromtxt("C:/Users/hp/Desktop/Data Analyst/S28 - A Loan Data Example with NumPy/loan-data.csv", delimiter = ';', skip_header = 1)
data

array([[4.8010226e+07,           nan, 3.5000000e+04, ...,           nan,
                  nan, 9.4529600e+03],
       [5.7693261e+07,           nan, 3.0000000e+04, ...,           nan,
                  nan, 4.6797000e+03],
       [5.9432726e+07,           nan, 1.5000000e+04, ...,           nan,
                  nan, 1.9698300e+03],
       ...,
       [5.0415990e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 2.1856400e+03],
       [4.6154151e+07,           nan,           nan, ...,           nan,
                  nan, 3.1994000e+03],
       [6.6055249e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 3.0190000e+02]])

now removing the white spaces any

In [5]:
data = np.genfromtxt("C:/Users/hp/Desktop/Data Analyst/S28 - A Loan Data Example with NumPy/loan-data.csv", delimiter = ';', skip_header = 1, autostrip = True)
data

array([[4.8010226e+07,           nan, 3.5000000e+04, ...,           nan,
                  nan, 9.4529600e+03],
       [5.7693261e+07,           nan, 3.0000000e+04, ...,           nan,
                  nan, 4.6797000e+03],
       [5.9432726e+07,           nan, 1.5000000e+04, ...,           nan,
                  nan, 1.9698300e+03],
       ...,
       [5.0415990e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 2.1856400e+03],
       [4.6154151e+07,           nan,           nan, ...,           nan,
                  nan, 3.1994000e+03],
       [6.6055249e+07,           nan, 1.0000000e+04, ...,           nan,
                  nan, 3.0190000e+02]])

checking the missing values

In [6]:
np.isnan(data)

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False],
       ...,
       [False,  True, False, ...,  True,  True, False],
       [False,  True,  True, ...,  True,  True, False],
       [False,  True, False, ...,  True,  True, False]])

In [7]:
np.isnan(data).sum()

88005

In [8]:
temp_fill = np.nanmax(data) + 1   #a filler for all the  missing entries of the dataset

In [9]:
temp_mean = np.nanmean(data, axis = 0)  #hold the mean of every column

C:\Users\hp\AppData\Local\Temp\ipykernel_10256\3200530536.py:1: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(data, axis = 0)  #hold the mean of every column


In [10]:
temp_mean  #represent mean values of each column

array([5.40158092e+07,            nan, 1.52734632e+04,            nan,
       1.53110421e+04,            nan, 1.66172948e+01, 4.40922179e+02,
                  nan,            nan,            nan,            nan,
                  nan, 3.14385094e+03])

now filling the missing values

In [11]:
temp_stats = np.array([np.nanmin(data, axis = 0), temp_mean , np.nanmax(data , axis = 0)])
temp_stats  #The temp_stats array contains the minimum, mean and maximum values of each column.

C:\Users\hp\AppData\Local\Temp\ipykernel_10256\2631524911.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(data, axis = 0), temp_mean , np.nanmax(data , axis = 0)])


array([[3.73332000e+05,            nan, 1.00000000e+03,            nan,
        1.00000000e+03,            nan, 6.00000000e+00, 3.14200000e+01,
                   nan,            nan,            nan,            nan,
                   nan, 0.00000000e+00],
       [5.40158092e+07,            nan, 1.52734632e+04,            nan,
        1.53110421e+04,            nan, 1.66172948e+01, 4.40922179e+02,
                   nan,            nan,            nan,            nan,
                   nan, 3.14385094e+03],
       [6.86165190e+07,            nan, 3.50000000e+04,            nan,
        3.50000000e+04,            nan, 2.89900000e+01, 1.37297000e+03,
                   nan,            nan,            nan,            nan,
                   nan, 4.19136200e+04]])

# splitting the dataset

splitting into string and numeric

In [12]:
col_string = np.argwhere(np.isnan(temp_mean))
col_string

array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]], dtype=int64)

In [13]:
col_string = np.argwhere(np.isnan(temp_mean)).squeeze()
col_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [14]:
col_numeric = np.argwhere(np.isnan(temp_mean)== False).squeeze()   #Compute the mean along the columns and Find the column indices where the mean is NaN
col_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

# Reimporting the dataset

In [15]:
string_data = np.genfromtxt("C:/Users/hp/Desktop/Data Analyst/S28 - A Loan Data Example with NumPy/loan-data.csv", delimiter = ';', 
                            skip_header = 1,
                           autostrip = True,
                           usecols = col_string,
                           dtype = str)
string_data

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
        'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
        'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726',
        'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
        'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
        'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249',
        'IL']], dtype='<U69')

In [16]:
numeric_data = np.genfromtxt("C:/Users/hp/Desktop/Data Analyst/S28 - A Loan Data Example with NumPy/loan-data.csv", delimiter = ';', 
                           autostrip = True,
                           skip_header = 1,
                           usecols = col_numeric,
                           filling_values = temp_fill)
numeric_data

array([[4.8010226e+07, 3.5000000e+04, 3.5000000e+04, 1.3330000e+01,
        1.1848600e+03, 9.4529600e+03],
       [5.7693261e+07, 3.0000000e+04, 3.0000000e+04, 6.8616520e+07,
        9.3857000e+02, 4.6797000e+03],
       [5.9432726e+07, 1.5000000e+04, 1.5000000e+04, 6.8616520e+07,
        4.9486000e+02, 1.9698300e+03],
       ...,
       [5.0415990e+07, 1.0000000e+04, 1.0000000e+04, 6.8616520e+07,
        6.8616520e+07, 2.1856400e+03],
       [4.6154151e+07, 6.8616520e+07, 1.0000000e+04, 1.6550000e+01,
        3.5430000e+02, 3.1994000e+03],
       [6.6055249e+07, 1.0000000e+04, 1.0000000e+04, 6.8616520e+07,
        3.0997000e+02, 3.0190000e+02]])

In [17]:
header_full = np.genfromtxt("C:/Users/hp/Desktop/Data Analyst/S28 - A Loan Data Example with NumPy/loan-data.csv", delimiter = ';', 
                           autostrip = True,
                           skip_footer = data.shape[0],
                           usecols = col_numeric,
                           dtype = str)
header_full

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment',
       'total_pymnt'], dtype='<U11')

In [18]:
header_string , header_numeric = header_full[col_string], header_full[col_numeric]

IndexError: index 8 is out of bounds for axis 0 with size 6